kind: pipeline
type: kubernetes
name: build

steps:
  #  - name: build
  #    image: plugins/docker
  #    settings:
  #      use_cache: true
  #      username:
  #        from_secret: dockerhub_username
  #      password:
  #        from_secret: dockerhub_password
  #      repo: sakyavarro/blog
  #      tags: latest

    - name: deploy_production
      image: pelotech/drone-helm3
      settings:
        namespace: varroreve
        mode: upgrade
        chart: ./helm
        release: blog-staging
        kube_api_server:
          from_secret: kube_api_server
        kube_token:
          from_secret: kube_token
        skip_tls_verify: true

#  - name: notify
#    image: lddsb/drone-dingtalk-message
#    settings:
#      token:
#        from_secret: dingtalk_token_insta_bot_drone_1
#      type: markdown

trigger:
  branch:
    - master



