kind: pipeline
type: kubernetes
name: build

steps:
  #  - name: build
  #    image: plugins/docker
  #    settings:
  #      use_cache: true
  #      username:
  #        from_secret: dockerhub_username
  #      password:
  #        from_secret: dockerhub_password
  #      repo: sakyavarro/blog
  #      tags: latest

#  - name: deploy_production
#    image: pelotech/drone-helm3
#    settings:
#      namespace: varroreve
#      mode: upgrade
#      chart: ./helm
#      release: blog-staging
#      kube_api_server: http://kuboard.varro.buzz/k8s-api
#      kube_token: QKg95nirOm1Y8YpLmZjPM_7RZRw2WWbQq9CBrF7M4xUPhgMbNo4Inb6bBVHAzstcOiac-MaMzsejUlilt19JUVwJV3d5xP-mgcB83pXBXoRrS0BxX1133x5V4CH38zjnO_NKRsCcSCER7Oozmp2fOrmqtAcK0iZ89g7utmYlsF3h4uti356R41p-k9pzB41I8OoWtVFQNK6S8tzsMgoKhZxqZSZcCn-b3rzCvQ6T68x3f-4wC1naNRkxqLEi9dbiX3emNqrCAnxHLfE3X3RFUuMVv-yyNeM_loT5JdU_ZFwbwEHriDlw2vOusjB_3a0cvHBJCkD954QIdy0A5J6fow
#      debug: true
#      skip_tls_verify: true
#    environment:
#      KUBE_API_SERVER: http://kuboard.varro.buzz/k8s-api
#      KUBE_TOKEN: QKg95nirOm1Y8YpLmZjPM_7RZRw2WWbQq9CBrF7M4xUPhgMbNo4Inb6bBVHAzstcOiac-MaMzsejUlilt19JUVwJV3d5xP-mgcB83pXBXoRrS0BxX1133x5V4CH38zjnO_NKRsCcSCER7Oozmp2fOrmqtAcK0iZ89g7utmYlsF3h4uti356R41p-k9pzB41I8OoWtVFQNK6S8tzsMgoKhZxqZSZcCn-b3rzCvQ6T68x3f-4wC1naNRkxqLEi9dbiX3emNqrCAnxHLfE3X3RFUuMVv-yyNeM_loT5JdU_ZFwbwEHriDlw2vOusjB_3a0cvHBJCkD954QIdy0A5J6fow


  - name: deploy
    image: bitsbeats/drone-helm3
    commands:
      - cat /root/.kube/config
    settings:
      kube_api_server: http://kuboard.varro.buzz/k8s-api
      kube_token: eyJhbGciOiJSUzI1NiIsImtpZCI6IldaTEdWem53VFVrMHBXOUYxT3A1WWo0S0MyOWhSUnpaa0ZPUjlXc3pCMVEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJ2ZWxlcm8tc2VydmVyLXRva2VuLWt3cmtwIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InZlbGVyby1zZXJ2ZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIxNmQxNTZmYi1iNWI2LTRmYmQtOTgxMi0wOWJiOTQ1MTVmOTgiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06dmVsZXJvLXNlcnZlciJ9.RovnTIBcAHfo8hwRuv8vkWydNxtQdXSKJ-F8Bgz2bftBQu3TppszLNUvJE5YXbfLhlcCh8eP_O4S0PAJ6ft3fVmvRDjuWXuLZbkaTKx_7a2ApVZD_wqHsoKPZ5fbt3Ed8SQvVhlZufiaQPFJK3oB6PcQJCIH9XRpL4EMoVF-x70b2mmXbOM2KV7fkAqaP5a4TFB4lrC1pd7VR88bi4pbae_gFPDnNkuL3QJ9JQJ-cps3YRgimqlHvlAnZsmN5jkArXZhzKjwaDc-vPOz2LzjNeLrBJQEklG7mkV351qC-2xy7lz7K750in-3BCcXAPOwxcQY9GINUMNEmBgyIU47WA
      namespace: varroreve
      chart: ./helm
      release: blog-staging
      wait: true
      force: true
      debug: true


#  - name: notify
#    image: lddsb/drone-dingtalk-message
#    settings:
#      token:
#        from_secret: dingtalk_token_insta_bot_drone_1
#      type: markdown

trigger:
  branch:
    - master
