kind: pipeline
type: kubernetes
name: build

steps:
#  - name: build
#    image: plugins/docker
#    settings:
#      use_cache: true
#      username:
#        from_secret: dockerhub_username
#      password:
#        from_secret: dockerhub_password
#      repo: sakyavarro/blog
#      tags: latest

  - name: deploy
    image: bitsbeats/drone-helm3
    settings:
      kube_api_server: http://kuboard.varro.buzz/k8s-api/
      kube_token:
        from_secret: kubernetes_token
      kube_certificate:
        from_secret: ca
      namespace: varroreve
      chart: ./helm
      release: blog-staging
      wait: true
      force: true


#  - name: notify
#    image: lddsb/drone-dingtalk-message
#    settings:
#      token:
#        from_secret: dingtalk_token_insta_bot_drone_1
#      type: markdown

trigger:
  branch:
    - master
