kind: pipeline
type: kubernetes
name: build

steps:
  - name: docker_build
    image: plugins/docker
    settings:
      use_cache: true
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: sakyavarro/blog
      tags: latest

#  - name: dingtalk
#    image: lddsb/drone-dingtalk-message
#    settings:
#      token:
#        from_secret: dingtalk_token_insta_bot_drone_1
#      type: markdown

trigger:
  branch:
    - master
