kind: pipeline
type: kubernets
name: build

steps:
  - name: build
    image: node
    pull: if-not-exists # always never
    environment:
      KEY: VALUE
    commands:
      - echo $KEY
      - npm install -g hexo-cli
      - npm install
      - hexo -v
      - hexo -g
      - ls
      - ls ./public

  - name: dingtalk
    image: lddsb/drone-dingtalk-message
    settings:
      token: 117ee9107800e43fd7ec6a2871c34a5769e5a8419e57df3d2a90cd4141117e46
      type: markdown

trigger:
  branch:
    - master