kind: pipeline
type: kubernetes
name: build

steps:
#  - name: build
#    image: plugins/docker
#    settings:
#      use_cache: true
#      username:
#        from_secret: dockerhub_username
#      password:
#        from_secret: dockerhub_password
#      repo: sakyavarro/blog
#      tags: latest

  - name: deploy
    image: bitsbeats/drone-helm3
    settings:
      kube_api_server: http://kuboard.varro.buzz/k8s-api/
      kube_token: eyJhbGciOiJSUzI1NiIsImtpZCI6IldaTEdWem53VFVrMHBXOUYxT3A1WWo0S0MyOWhSUnpaa0ZPUjlXc3pCMVEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ2YXJyb3JldmUiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiZGVwbG95ZXItdG9rZW4tcXRwcXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVwbG95ZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIxZGQ0NmMwNC1jNTA2LTQzNzEtODRhZS02NzNmMWFjYzA3OWQiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6dmFycm9yZXZlOmRlcGxveWVyIn0.YEHaAIPfe1TPmhP73MjHbHP7IWvsjNaBdn6uGI35pw3fgG33ApRcafC_ODevUYMWSt8vunici3sRyGR_R_P-HaDK-C8IROLrAHWh38zfjF2UlDqakdsXFwN-GwwoRp2H2XVOSWjTf6RzROu5kZdcIdmbFQGuZktHEXeFPwBHufnUP5uSR1cvrM8X0voMIru4Kd2eC-a6zEMDRxROX9aHrCol8baxHEYATTphYAcv84jRs9h5z4HPkTHLe1FQ4IlfKmXadgUZ_QLS4J1AN938hSBiFuK_QMSQXFl2QbyjIIlXWsEfMUYX8abDGvKMOHvKdYH1E45NEpxaiQGTuIuKow
#      kube_certificate:
#        from_secret: kubernetes_ca
      namespace: varroreve
      chart: ./helm
      release: blog-staging
      wait: true
      force: true


#  - name: notify
#    image: lddsb/drone-dingtalk-message
#    settings:
#      token:
#        from_secret: dingtalk_token_insta_bot_drone_1
#      type: markdown

trigger:
  branch:
    - master
