kind: pipeline
type: kubernetes
name: build

steps:
#  - name: build
#    image: plugins/docker
#    settings:
#      use_cache: true
#      username:
#        from_secret: dockerhub_username
#      password:
#        from_secret: dockerhub_password
#      repo: sakyavarro/blog
#      tags: latest

  - name: deploy
    image: bitsbeats/drone-helm3
    settings:
#      kube_api_server: http://kuboard.varro.buzz/k8s-api/
#      kube_token: eyJhbGciOiJSUzI1NiIsImtpZCI6IldaTEdWem53VFVrMHBXOUYxT3A1WWo0S0MyOWhSUnpaa0ZPUjlXc3pCMVEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJoZWxtLXRva2VuLW16NGhuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImhlbG0iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI5MGNlMWYyNC0zYjZhLTQyMDctYjRkYy04MDU2NTE2NjkyZTYiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06aGVsbSJ9.CiuIGOPc_JIil1TOiJZN3e48ffcwRNaceznsXwYagdimT9USfOu1ugMLV3wy42DSHt5h2YPUpt7QLulzvvc2ZjhWNz8CO8YwEoS8CyOffZ022wCm-wWau-He4O6-q6mj5PXrXjQHTLrEvgEXld9lsxKbnlaEScx0STazK8TELxnKIGLJ95RGGcVTmzYc5rhZpQwcNZeZlmfFH8rTPDERHqFdL3y0HdbPxuNITtCQDHCSpgH8_muAaN_SLAQgtPuLA8ZL1URrZbgZjXWWMxfJjUZMdkJQG-sbfTaorWXJTvP9H3XkEpgJ3GmypNx_y38yEYzerEtdWZrbsrKloPgp4g
#      kube_certificate: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01ERXlNVEEyTWpneU5sb1hEVE13TURFeE9EQTJNamd5Tmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT0dzClVCazl2Y3FLUk81Z2Rua3B1bVpwVDBzVzRXOUppMEduL1VSUWJHMVRic3JDZkoyWTFOZTBxSFQybndhMG5JS3oKMllxOERQRkVBdVFqQTc5Mi80KysxSnlCRjhhN3QrSXFvZDRqb20rdVVObU9KUmpPeGdFbk5PallpTDB5d09yZwowRTlHMVVKWlM4NkhZMmFkVlpiWitvWWY1ZVdxbW1aeGlaTURxMnRzN3pOTVFSSmJHN2RGREUvMSt4dWw0Wm13Ckpsd2MvZDRFVjhRNktNUnlOZE43bmJpNFJ4M1czUWFVR3FIcjhXNkJmNkxndmhmZHdRa2xmTDhCVFlzMXpFZE0KUE5ucW55SWljajF2blpSVFZXY1IxMjRsTmZkcFNNczUremgyOVpBaVdBRzlXQkRreWR6cmFKNTR4bVIxMG5VUQpnZU5hdU5iRm54VUEvWE1veThjQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFIcVo4eG5yeVVObWN6YW5DN1JtNmRNYWVCVEYKc0UvWi9WRWlQcEpVSjEyU3l4cnlVSTBSd1p0cHRnVmVDTnZMRG95SHc4UGhQMkc0WGkxb1JaSWVVeVlBUlBIWgpaclErMHpRUTFWK1B3Ui9LbGgzTzJCMHNiMVFZeXRvdzhYQ0FyaTliYSttRnB5VXNwSGtFZncrUmY5TFl0L1M2ClVDQXhQdXFYNHRQVHYwRGdLSkE3cWIwbFZzdlY4Y2lBTVRoRkthSStjTHNWcGtrS2tmeXQwYzd1UDV1ODBvdncKQlE0MVRVaXl0N3FvNmtFMWpFRHhDM0RUM0JUOXUzWDI0NzJGL1hWMFpSUzc5WEhKcnp5NFNRa2hOQ3lVTGllOApBbzMraW83TkVMZldhVDNzTCtWTi9aVURRclZHeU0zNWl5NHZIbmtjN1lXVC9uTnUyN0haREV6SlZ5MD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      namespace: varroreve
      chart: ./helm
      release: blog-staging
      wait: true
      force: true


#  - name: notify
#    image: lddsb/drone-dingtalk-message
#    settings:
#      token:
#        from_secret: dingtalk_token_insta_bot_drone_1
#      type: markdown

trigger:
  branch:
    - master
