kind: pipeline
type: kubernetes
name: build

steps:
#  - name: build
#    image: plugins/docker
#    settings:
#      use_cache: true
#      username:
#        from_secret: dockerhub_username
#      password:
#        from_secret: dockerhub_password
#      repo: sakyavarro/blog
#      tags: latest

#  - name: deploy_production
#    image: pelotech/drone-helm3
#    settings:
#      namespace: varroreve
#      helm_command: upgrade
#      chart: ./helm
#      release: blog-staging
#      api_server: http://kuboard.varro.buzz/k8s-api/
#      kubernetes_token: eyJhbGciOiJSUzI1NiIsImtpZCI6IldaTEdWem53VFVrMHBXOUYxT3A1WWo0S0MyOWhSUnpaa0ZPUjlXc3pCMVEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJoZWxtLXRva2VuLW16NGhuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImhlbG0iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI5MGNlMWYyNC0zYjZhLTQyMDctYjRkYy04MDU2NTE2NjkyZTYiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06aGVsbSJ9.CiuIGOPc_JIil1TOiJZN3e48ffcwRNaceznsXwYagdimT9USfOu1ugMLV3wy42DSHt5h2YPUpt7QLulzvvc2ZjhWNz8CO8YwEoS8CyOffZ022wCm-wWau-He4O6-q6mj5PXrXjQHTLrEvgEXld9lsxKbnlaEScx0STazK8TELxnKIGLJ95RGGcVTmzYc5rhZpQwcNZeZlmfFH8rTPDERHqFdL3y0HdbPxuNITtCQDHCSpgH8_muAaN_SLAQgtPuLA8ZL1URrZbgZjXWWMxfJjUZMdkJQG-sbfTaorWXJTvP9H3XkEpgJ3GmypNx_y38yEYzerEtdWZrbsrKloPgp4g

  - name: deploy
    image: bitsbeats/drone-helm3
    settings:
      kube_api_server: http://kuboard.varro.buzz/k8s-api/
      kube_token: eyJhbGciOiJSUzI1NiIsImtpZCI6IldaTEdWem53VFVrMHBXOUYxT3A1WWo0S0MyOWhSUnpaa0ZPUjlXc3pCMVEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJrdWJvYXJkLXVzZXItdG9rZW4tam1jaGIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoia3Vib2FyZC11c2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZTgwZmIzZjUtNzQxNy00YWI1LWE2NjUtNDIxYmRhOTI0ZGFjIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmt1Ym9hcmQtdXNlciJ9.QKg95nirOm1Y8YpLmZjPM_7RZRw2WWbQq9CBrF7M4xUPhgMbNo4Inb6bBVHAzstcOiac-MaMzsejUlilt19JUVwJV3d5xP-mgcB83pXBXoRrS0BxX1133x5V4CH38zjnO_NKRsCcSCER7Oozmp2fOrmqtAcK0iZ89g7utmYlsF3h4uti356R41p-k9pzB41I8OoWtVFQNK6S8tzsMgoKhZxqZSZcCn-b3rzCvQ6T68x3f-4wC1naNRkxqLEi9dbiX3emNqrCAnxHLfE3X3RFUuMVv-yyNeM_loT5JdU_ZFwbwEHriDlw2vOusjB_3a0cvHBJCkD954QIdy0A5J6fow
      namespace: varroreve
      chart: ./helm
      release: blog-staging
      wait: true
      force: true


#  - name: notify
#    image: lddsb/drone-dingtalk-message
#    settings:
#      token:
#        from_secret: dingtalk_token_insta_bot_drone_1
#      type: markdown

trigger:
  branch:
    - master
