language: node_js

sudo: required

node_js: stable

addons:
  ssh_known_hosts: 118.24.102.34

branches:
  only:
    - deploy

cache:
  directories:
    - node_modules

# 解密秘钥
before_install:
  - openssl aes-256-cbc -K $encrypted_162432d46384_key -iv $encrypted_162432d46384_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

# 安装 hexo
install:
  - npm install -g hexo-cli
  - npm install
  - npm install hexo-deployer-git --save

# 清除缓存，生成静态文件，推送代码到 master 分支, 部署到 Github Pages
script:
  - hexo clean
  - hexo generate
  - git config --global user.name "varro-travis"
  - git config --global user.email "542109010@qq.com"
  - sed -i "s/gh_token/${GITHUB_REPO_TOKEN}/g" ./_config.yml
  - hexo deploy

# 部署代码到服务器
after_success:
  - ssh deployer@sakyavarro.cn -o stricthostkeychecking=no -i /tmp/deploy_rsa 'cd /var/www
    && rm -rf hexo && git clone https://github.com/SakyaVarro/sakyavarro.github.io.git hexo && chmod -R 777 hexo && echo done && exit'

# 抓取简历, 生成 PDF, 上传到七牛云
#after_script:
#  - docker pull arachnysdocker/athenapdf
#  - curl -v -o qshell.zip http://devtools.qiniu.com/qshell-v2.3.5.zip
#  - ls -l qshell.zip
#  - unzip qshell.zip
#  - mv qshell_linux_x64 qshell
#  - docker run --rm -v $(pwd):/converted/ arachnysdocker/athenapdf athenapdf
#    http://www.sakyavarro.cn/resume resume.pdf
#  - "./qshell account $QINIU_AK $QINIU_SK varro_test"
#  - "./qshell fput varro resume.pdf resume.pdf -w"
#  - "echo 'http://cdn.sakyavarro.cn/resume.pdf' > refresh_list.text"
#  - "./qshell cdnrefresh -i refresh_list.text"